// Generated by VBR transpiler — web/WASM target
//
// Build with: wasm-pack build --target bundler
//
// Required Cargo.toml additions:
//   [lib]
//   crate-type = ["cdylib"]
//   [dependencies]
//   vbr_forms_web    = { path = "../vbr_forms_web" }
//   wasm-bindgen     = "0.2"
//   serde-wasm-bindgen = "0.6"

use wasm_bindgen::prelude::*;
use vbr_forms_web::{FormSnapshot, ControlState};

#[wasm_bindgen]
pub struct HelloWorld {
    user_name: String,
    status_message: String,
}

#[wasm_bindgen]
impl HelloWorld {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        HelloWorld {
            user_name: String::new(),
            status_message: String::new(),
        }
    }

    pub fn initial_snapshot(&self) -> JsValue {
        serde_wasm_bindgen::to_value(&self.snapshot()).unwrap()
    }

    pub fn name_changed(&mut self, value: String) -> JsValue {
        if !value.is_empty() {
            self.status_message = format!("{}{}{}", "Hello, ", value, "!");
        } else {
            self.status_message = "Type a name above.".to_string();
        }
        serde_wasm_bindgen::to_value(&self.snapshot()).unwrap()
    }

    pub fn cancel(&mut self) -> JsValue {
        serde_wasm_bindgen::to_value(&self.snapshot()).unwrap()
    }

    pub fn ok(&mut self) -> JsValue {
        self.status_message = format!("{}{}{}", "Welcome, ", self.user_name, "!");
        serde_wasm_bindgen::to_value(&self.snapshot()).unwrap()
    }

    fn snapshot(&self) -> FormSnapshot {
        FormSnapshot {
            controls: vec![
                ControlState { id: "user_name".to_string(), value: self.user_name.clone(), caption: None, visible: true, enabled: true, error: None },
                ControlState { id: "status_message".to_string(), value: self.status_message.clone(), caption: None, visible: true, enabled: true, error: None },
            ],
        }
    }
}
